let locationSearch = location.search;
let locationSearchParams = new URLSearchParams(locationSearch);
let productIDParam = locationSearchParams.get("id");


let productArray = [
{id: 1, name: "Assassins Creed Shadows", characterName: "Yasuke", characterImg: "/sabzlearn/js/ShoppingCart/gameCart/characters/Yasuke.webp" , img1: "https://preview.redd.it/assassins-creed-shadows-in-engine-screenshot-v0-akxjosgw8m0d1.jpeg?width=640&crop=smart&auto=webp&s=1ba4eb86135daa8fd00f337e84fe328925ad2d83",img2: "https://www.univers-simu.com/wp-content/uploads/2024/06/assassin-creed-shadows.jpg",img3: "https://assets-prd.ignimgs.com/2024/06/10/shadows-gameplay-1718050115580.png",img4: "https://i.jeuxactus.com/datas/jeux/a/s/assassin-s-creed-shadows/xl/assassin-s-creed-shadows-664603a51f963.jpg",img5: "https://static.gosugamers.net/12/72/13/26c3c80f4ccd8b458bf863847295794329c0971598132e642da5682e11.webp?w=1600",img6: "https://media.altchar.com/prod/images/gm_article_promo_image/d1b85870f7ec-screenshot-2024-06-11-011008.jpg",img7: "https://static1.thegamerimages.com/wordpress/wp-content/uploads/2024/06/naoe-in-assassins-creed-shadows.jpg", price: 79.99, headerImg: "https://images8.alphacoders.com/136/1362729.jpeg", characterInfo: "Yasuke (弥助; born c. 1555) was an African samurai who served the Japanese warlord Oda Nobunaga. In 1579, the Portuguese Empire brought him as a slave to the port city of Sakai.[2][3] According to the Chronicle of Nobunaga, he entered into Oda's service a few years later after capturing his attention as the first African man he had ever met and impressing him with his strong stature and intelligence. <br> In 1581, he invaded Iga Province on behalf of his lord, devastating the region. Despite having destroyed Fujibayashi Naoe's home, Yasuke later allied himself with the young Iga Assassin, assisting her in not just intelligence-gathering but assassinations as well. <br> Yasuke was a thoughtful and intelligent man, who was able to learn the Japanese people's language, customs, and martial arts quickly upon arriving in their country. His respect for the local culture enabled his adaptation to his new environment. These qualities, alongside his physical prowess and aptitude in combat, were what earned him Oda Nobunaga's respect. His down-to-earth sensibilities complemented the fiery and passionate temperament of his later ally Fujibayashi Naoe.", bgColors: "#221513, #BC0E0B, #450202, #A8120D"},
{id: 2, name: "Assassins Creed Mirage", characterName: "Basim", characterImg: "/sabzlearn/js/ShoppingCart/gameCart/characters/basim.png" , img1: "https://assetsio.gnwcdn.com/Assassins-Creed-Mirage-official-screenshots-1.jpg?width=1600&height=900&fit=crop&quality=100&format=png&enable=upscale&auto=webp",img2: "https://cdn.mos.cms.futurecdn.net/pP4idKwBFCH9vGLkf6g87c-1200-80.jpg",img3: "https://www.gameinformer.com/sites/default/files/styles/full/public/2023/06/12/269549ea/acmirage_01.jpg",img4: "https://www.notebookcheck.net/fileadmin/Notebooks/News/_nc3/Assassins_Creed_Mirage_header.jpg",img5: "https://gamingbolt.com/wp-content/uploads/2022/09/assassins-creed-mirage-image-4.jpg",img6: "https://i0.wp.com/explosionnetwork.com/wp-content/uploads/2023/09/44e7c-assassins-creed-mirage-release-date-gameplay-trailer.jpg?fit=1280%2C720&ssl=1",img7: "https://www.playstationlifestyle.net/wp-content/uploads/sites/9/2023/06/acm1.jpg?w=1024", price: 39.99, headerImg: "https://techsyndrome.in/wp-content/uploads/2023/10/Assassins-Creed-Mirage-Screenshot-2023.10.02-19.45.17.85.png" , characterInfo: "Basim Ibn Ishaq (Arabic: بَاسِمُ بْنُ إِسْحَاقَ; born c. 844), also stylized Basim ibn Is'haq, is a human incarnation of the Isu Loki and a former Master Hidden One active during the 9th century. <br> The son of Ishaq, the architect responsible for designing Samarra's renowned Great Mosque, Basim was orphaned at a young age and made a living as a thief, joining a network led by Dervis in Anbar. However, he was frequently tormented by nightmares of a djinn, which were in fact a representation of his repressed memories as Loki. At the same time, Loki's personality took the form of Nehal, whom Basim perceived as his childhood best friend. <br> In 861, Basim became acquainted with the Master Hidden One Roshan and sought to impress her in order join the brotherhood. However, his attempt to steal a Memory Seal sought by the Hidden Ones resulted in his accidental murder of the caliph Al-Mutawakkil. Becoming a fugitive, Basim fled Anbar with Roshan and traveled to Alamut, where he joined the Hidden Ones. <br> Basim played an important role in the brotherhood's struggle against the Order of the Ancients in Baghdad, assassinating many of the Order's high-ranking members. However, he also began to question his own nature and, after defeating Roshan, who sought to prevent him from learning the truth, entered the Alamut Temple.", bgColors: "#3D444E, #AC7A55, #1E1923, #83563C"},
{id: 3, name: "Assassins Creed Valhalla",characterName: "Eivor", characterImg: "/sabzlearn/js/practice/characters/elvor.png" , img1: "https://staticctf.ubisoft.com/J3yJr34U2pZ2Ieem48Dwy9uqj5PNUQTn/44sZCER9jQwTTs3LxttbYt/91a4a4e6651389b308a0cc1b36dc7dbd/Combat.jpg",img2: "https://www.gameinformer.com/sites/default/files/styles/thumbnail/public/2020/11/08/64cf8408/04_0.jpg",img3: "https://cdn.vox-cdn.com/thumbor/7Z6VNCuy8Ink2BxJnxC0JcVKkAI=/0x0:3840x2160/1200x675/filters:focal(925x815:1539x1429)/cdn.vox-cdn.com/uploads/chorus_image/image/67630691/ACV_Iconic_Landscape_Stonehenge.0.jpg",img4: "https://www.nme.com/wp-content/uploads/2020/07/071720-Assassins-Creed-Valhalla-Ubisoft.jpg",img5: "https://akm-img-a-in.tosshub.com/sites/itgaming/resources/202010/story/assassin_s_creed_valhalla_gameplay_101920015217.jpg",img6: "https://miro.medium.com/v2/da:true/resize:fit:1200/0*dSZCihv-ih_5kuU4",img7: "https://cdn.wallpaper.tn/large/Assassin'S-Creed-Valhalla-Wallpaper-150287.jpg", price: 29.99, headerImg: "https://wallpaper.forfun.com/fetch/7b/7bea3917b92c344e027f8c40a6a890b4.jpeg" , characterInfo: "Eivor Varinsdottir (Runic: ᛅᛁᚢᛅᚱ; born 847), renowned as the Wolf-Kissed, was a Viking shieldmaiden and jarlskona from Norway who raided in what would later become England during the late 9th century. She was the incarnation of the Isu Odin, the chief of the Æsir who was revered as a god in Germanic and Norse mythology. She is also the ancestor of the Abstergo Industries security contractor and Assassin Yu Shu Lien. <br> Once an adult, Eivor would frequently raid settlements affiliated with Kjotve while Sigurd sailed around Europe. Following her brother's return to Norway in 872, Eivor met the Hidden Ones Basim Ibn Ishaq and Hytham and was gifted a Hidden Blade, which she used in combat against her enemies. After killing Kjotve and taking his lands with assistance from the army of Guthorm the Wise, Eivor followed her brother Sigurd to England after Styrbjorn ceded his kingdom to Harald Fairhair, a decision opposed by many of the Raven Clan, including Sigurd. <br> Eivor and her clan settled in Ledecestrescire, establishing the settlement of Ravensthorpe and spent the next few years building her settlement and securing alliances with the kingdoms within England. These alliances included the Great Summer Army, the Sons of Ragnar, Clan Hemmingsons, and more.", bgColors: "#47b0ba,#717fae,#2B3137,#dc9f97"},
{id: 4, name: "Assassins Creed Odyssey",characterName: "Alexios", characterImg: "/sabzlearn/js/practice/characters/alexios.png" , img1: "https://d1lss44hh2trtw.cloudfront.net/assets/article/2018/08/27/assassins-creed-odyssey-exclusive-open-world-gameplay-header_feature.jpg",img2: "https://www.trueachievements.com/customimages/082348.jpg",img3: "https://www.psu.com/wp/wp-content/uploads/2019/07/AssassinsCreedOdysseyAtlantis-1024x576.jpg",img4: "https://img.playstationtrophies.org/images/screenshots/7475/med_ab48539c-9024-4d4c-a516-aae766c04947_ACOD_screen_DialogueWithMercenary_180821_930am_CEST_1534778702.jpg",img5: "https://i.redd.it/zf4lrdkqiht21.jpg",img6: "https://i.ytimg.com/vi/lPnzBZttRh8/maxresdefault.jpg",img7: "https://cdn.wccftech.com/wp-content/uploads/2018/09/assassins_creed_odyssey_battle_spear-scaled.jpg", price: 69.99, headerImg: "https://steamuserimages-a.akamaihd.net/ugc/975487861754690970/9D76AE412BA18CA306BF74281275504F95C7FA08/" , characterInfo: "Alexios (Greek: Αλεξιος; 451 BCE . 422 BCE), also known as Deimos, was a Sage of the Cult of Kosmos, an organization active in ancient Greece. Alongside his older half-sister, the famed misthios Kassandra, he was a grandchild of King Leonidas I of Sparta through his mother, Myrrine, as well as a hybrid. His unique heritage made him the target of the Cult as an infant and a false oracle delivered by the Cult deceived Sparta into believing he had to be thrown off Mount Taygetos to his death. Although he survived the fall, Alexios was abducted by the Cultist Chrysis and forced to endure a cruel and torturous childhood. His harsh upbringing warped his mind, brainwashing him into becoming a weapon of the Cult convinced that he was their champion, Deimos. In reality, the other Cultists only saw him as a deranged beast which served their purposes.", bgColors: "#27446C, #3B2F22, #5D5526, #5E523C"},
{id: 5, name: "Assassins Creed Origins",characterName: "Bayek", characterImg: "/sabzlearn/js/practice/characters/Bayek.webp" , img1: "https://assets1.ignimgs.com/2017/08/22/aco-screen-bayekaya-interrogate-gc-170822-930am-cest-1503333980-1503437530690.jpg",img2: "https://i.ytimg.com/vi/A7kSzTatiNo/maxresdefault.jpg",img3: "https://cdn.mos.cms.futurecdn.net/WqSiSuG5Z58YcAsGHMu5iW-1200-80.jpg",img4: "https://imageio.forbes.com/blogs-images/games/files/2017/10/assassins-creed-origins4.jpg?height=399&width=711&fit=bounds",img5: "https://cdn.wccftech.com/wp-content/uploads/2017/06/ACO_screen_Pyramids_e3_170611_330pm_1497209515-scaled.jpg",img6: "https://www.lakebit.com/wp-content/uploads/2017/07/assassins-creed-origins-gameplay-video.jpg",img7: "https://gameranx.com/wp-content/uploads/2017/07/Assassins-Creed-Origins-1.jpg", price: 59.99, headerImg: "https://pixelz.cc/wp-content/uploads/2017/11/assassins-creed-origins-concept-art-uhd-8k-wallpaper.jpg" , characterInfo: "Bayek of Siwa (born c. 85 BCE), also known by the alias Amun, was one of the last Medjay of Egypt and the co-founder of the Hidden Ones alongside his wife, Aya. <br> Growing up in the remote village of Siwa, Bayek inherited the mantle of Medjay from his father, Sabu, and dedicated his life to protecting the security and welfare of his people. He also tried to raise his son, Khemu, in the Medjay ways, but this took a dramatic turn in 49 BCE, when Khemu was killed during an altercation with the Order of the Ancients, who had tried to interrogate Bayek to learn how to unlock the Siwa Vault. <br> Swearing vengeance on the Order, Bayek abandoned his Medjay duties and, alongside Aya, embarked on a quest to avenge their son by systematically assassinating every individual responsible. In process, they became allied with the exiled queen Cleopatra VII, who revealed that the Order's reach and power far exceeded their initial belief. Although wary, Bayek followed Aya's lead and pledged his service to Cleopatra as her personal Medjay, in the process embroiling himself in the Alexandrine Civil War against Ptolemy XIII. <br> Following the conflict's conclusion, Cleopatra and her ally, Julius Caesar, betrayed Bayek and Aya by aligning themselves with the Order. In response, Bayek gathered their allies to form the Hidden Ones, a secret brotherhood that swore to fight against the Order and safeguard peace and freedom.", bgColors: "#70482C, #110A09, #BC7427, #190D0A"},
{id: 6, name: "Assassins Creed Syndicate",characterName: "Fryes", characterImg: "/sabzlearn/js/practice/characters/fryes.png" , img1: "https://ew.com/thmb/LZGIj5NmwmxdjKzn0T6aj5Hcnjk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/assassins_creed_syndicate_gang_leader-8f0dd319e7604b1aa7f3fcbdb05bfb56.jpg",img2: "https://ew.com/thmb/pnH-zQNxgW0w_RfiUeVJQ4JG6jU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/assassins_creed_syndicate_cart_race-940b2dc7a9054187bc39fb170f7a58a6.jpg",img3: "https://ew.com/thmb/eP-uNxjXBAMm6SLJYoXhlWhLc_c=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/assassins_creed_syndicate_stealth-environmental_assassination-2f648faf25d34be4ae110c4a15139f60.jpg",img4: "https://ew.com/thmb/xeqaTbNySI-8pZJJfxJd6J75s-4=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/assassins_creed_syndicate_assassination-2b5bff85ed364e9aacba405bbc43fc3d.jpg",img5: "https://imageio.forbes.com/blogs-images/davidthier/files/2015/10/Assassins-Creed-Syndicate-2.jpg?format=jpg&height=900&width=1600&fit=bounds",img6: "https://cdn.wccftech.com/wp-content/uploads/2015/09/Syndicate-4.jpg",img7: "https://news-cdn.softpedia.com/images/news2/fresh-assassin-s-creed-syndicate-gameplay-video-focuses-on-jacob-and-evie-492408-2.jpg", price: 39.99, headerImg: "https://www.psu.com/wp/wp-content/uploads/2020/09/Assassins-Creed-Syndicate-PS4-Wallpapers-07.jpg" , characterInfo: "Sir Jacob Frye and Dame Evie Frye were twin siblings, born in 1847 in Crawley. They were raised and trained in the ways of the Assassins by their widowed father, Ethan. Unlike the carefree and impulsive Jacob, the studious Evie took her Assassin training very seriously and relished in her father's teachings. Evie preferred stealth over direct combat, and tended to meticulously plan out her approach before each mission. This often put her at odds with Jacob's more reckless and head-on methods. Despite their conflicting personalities and approaches, both Jacob and Evie went on to become Master Assassins of the British Brotherhood during the Victorian era. Jacob later gained further distinction by becoming a member of Queen Victoria's Order of the Sacred Garter. The Frye twins' legacy continued through Jacob's granddaughter, Lydia Frye, who was an Assassin active during World War I. Evie also had a descendant, the scientist and Assassin Jackie O'Connell.", bgColors: "#0B1929, #06091B, #3F0D1A, #30454A"},
{id: 7, name: "Assassins Creed Unity",characterName: "Arno", characterImg: "/sabzlearn/js/practice/characters/Arno.webp" , img1: "https://oyster.ignimgs.com/mediawiki/apis.ign.com/assassins-creed-5/e/ef/Acuscreencombatsworde31406094pmpst1402143761jpg-b685a9_640w.jpg",img2: "https://i0.wp.com/gaming-age.com/wp-content/uploads/2014/07/assassins-creed-unity_2.jpg?fit=1024%2C576&ssl=1&resize=1280%2C720",img3: "https://assets1.ignimgs.com/2014/08/16/assassinscreedunity-gamescom-80coopheistgc14081310amcet1407889511jpg-8de444.jpg",img4: "https://s3.amazonaws.com/prod-media.gameinformer.com/styles/body_default/s3/legacy-images/imagefeed/Watch%2011%20Minutes%20Of%20Gameplay%20In%20This%20Guided%20Gamescom%20Demo/Unity%2520gamescom%2520demo%2520610.jpg",img5: "https://i0.wp.com/artcentron.com/wp-content/uploads/2014/09/Assassins_Creed_Unity_SP_Arno-Escaping.jpg?fit=770%2C433&ssl=1",img6: "https://i.ytimg.com/vi/9-EffU9nxO4/maxresdefault.jpg",img7: "https://cdn.vox-cdn.com/thumbor/rCAFxmUkr8jSHyiPEPs63pZC5NY=/0x0:1920x1080/1600x900/cdn.vox-cdn.com/uploads/chorus_image/image/44398552/ac_unity.0.jpg", price: 29.99, headerImg: "https://i.ytimg.com/vi/Vp3F_xLKbPg/maxresdefault.jpg" , characterInfo: "Master Assassin of the French Brotherhood, active in the years surrounding the French Revolution and the Napoleonic Wars. He is also an ancestor of the Assassin Callum Lynch. <br> The only son of the Assassin Charles Dorian and his wife Marie, Arno was orphaned at a young age, with his mother leaving the family after discovering Charles' allegiance and his father being assassinated in 1776 by the American Templar Shay Cormac. François de la Serre, the Grand Master of the French Rite of the Templar Order, adopted Arno as his ward and raised him alongside his daughter Élise. Over the years, Arno and Élise became close friends, and later lovers. <br> In May of 1789, François was killed at the Palace of Versailles as part of a coup within the Templar Order, and Arno was framed for the murder. While imprisoned at the Bastille, he met the Master Assassin Pierre Bellec, who told Arno of his Assassin heritage. Wracked with guilt over his past failures, Arno joined the Brotherhood in the hopes of avenging his biological and adoptive fathers, while also working to uncover the true instigators of the French Revolution.", bgColors: "#245470, #6A0B12, #5A5D43, #34404E"},
{id: 8, name: "Assassins Creed Black Flag",characterName: "cenvey", characterImg: "/sabzlearn/js/practice/characters/cenvey.png" , img1: "https://assets1.ignimgs.com/vid/thumbnails/user/2013/10/11/Assassins-Creed-4-Black-Flag-silence.jpg",img2: "https://www.gameinformer.com/sites/default/files/styles/full/public/2023/07/03/25788f06/assassins_creed_4_jungle.png",img3: "https://s2.dmcdn.net/v/3Str51Zdo5h5qYsKG/x1080",img4: "https://image.alza.cz/products/MSX050/MSX050-07.jpg?width=500&height=500",img5: "https://images.pushsquare.com/09fafc7ba1949/assassins-creed-iv-black-flag.large.jpg",img6: "https://www.justpushstart.com/wp-content/uploads/2013/08/Assassins-Creed-4-Underwater-Treasure.jpg",img7: "https://www.gameinformer.com/s3/files/styles/body_default/s3/legacy-images/imagefeed/New%20Gameplay%20Video%20Shows%20Off%20High-Seas%20Action/ACIVBFreveal610.jpg", price: 19.99, headerImg: "https://lh3.googleusercontent.com/ynO32Ezm8SgmRAzXSHTTeZAebfxpfxCOgO2uXeynVe72LCrjoop9l8B0ih2d1PtbmuR4BfuHJAA_XWTvCHcPxCIyxA=s1280-w1280-h800" , characterInfo: "Edward James Kenway (1693 . 1735) was a Welsh-born British privateer-turned-pirate and a member of the West Indies and British Brotherhoods of Assassins. He was the father of Haytham Kenway, the founder of the Colonial Rite of the Templar Order, and the grandfather of Ratonhnhaké:ton, a prominent Colonial Assassin. Through this line, he is an ancestor of William and Desmond Miles, as well as Victor Flores Castillo. He is additionally an ancestor of Noa Kim. <br> Born to humble farmers, Edward always sought to acquire riches and fame. He became a privateer for the Royal Navy early in his life and, once accepted, found himself stationed in the West Indies. However, an abrupt end to the War of the Spanish Succession and the promise of gold, glory and fame eventually seduced him into a life of piracy. It was during this quest that Edward first encountered the Assassins and Templars, and became embroiled in their struggle.", bgColors: "#24231B, #45595F, #5D261F, #88857C"}
]



let body = document.querySelector("body");
let titleElem = document.querySelector("title");
let imgHeaderElem = document.querySelector(".imgHeader");
let mainTitleElem = document.querySelector(".mainTitle");

let imgElem1 = document.querySelector("#image-1");
let imgElem2 = document.querySelector("#image-2");
let imgElem3 = document.querySelector("#image-3");
let imgElem4 = document.querySelector("#image-4");
let imgElem5 = document.querySelector("#image-5");
let imgElem6 = document.querySelector("#image-6");
let imgElem7 = document.querySelector("#image-7");

let characterInfoH2Elem = document.querySelector(".characterInfoH2");
let characterInfoPElem = document.querySelector(".characterInfoP");
let characterInfoImg = document.querySelector(".characterImg");
let purchaseH1Elem = document.querySelector(".purchaseH1");


let mainProduct = productArray.find(function (product) {
  return product.id === parseInt(productIDParam);
});




  if(mainProduct){
    body.style.background = `linear-gradient(135deg, ${mainProduct.bgColors})`;
    titleElem.innerHTML = mainProduct.name;
    imgHeaderElem.src = mainProduct.headerImg;
    mainTitleElem.innerHTML = mainProduct.name;

    imgElem1.src = mainProduct.img1;
    imgElem2.src = mainProduct.img2;
    imgElem3.src = mainProduct.img3;
    imgElem4.src = mainProduct.img4;
    imgElem5.src = mainProduct.img5;
    imgElem6.src = mainProduct.img6;
    imgElem7.src = mainProduct.img7;

    characterInfoH2Elem.innerHTML = mainProduct.characterName;
    characterInfoPElem.innerHTML = mainProduct.characterInfo;
    characterInfoImg.src = mainProduct.characterImg;
    purchaseH1Elem.innerHTML = "Now You Can Order <br>" + mainProduct.name + "<br> $" + mainProduct.price;

    }


///////////////////purchase-btn/////////////////////

let purchaseLink = document.querySelector(".purchase-link");
let purchaseBtn = document.querySelector(".purchase-btn");


purchaseBtn.addEventListener("click", function(){
  purchaseLink.href = "http://127.0.0.1:5500/ShoppingCart/home/index.html?id=" + mainProduct.id;
})



/////////////////home btn///////////////

let homeBtn = document.querySelector(".homeBtn");

homeBtn.addEventListener("click" , function(){
  history.back();
})